/* $Id: Config.cmd,v 1.10 2004/02/22 23:03:23 smilcke Exp $ */

/*
 * Configuration script.
 * Generates global makefile.inc.
 *
 * Copyright (c) 1999-2000 knut st. osmundsen (knut.stange.osmundsen@pmsc.no)
 * Modified for BT-Drivers 2002 Stefan Milcke
 *
*/

Call RxFuncAdd 'SysLoadFuncs', 'RexxUtil', 'SysLoadFuncs';
Call SysLoadFuncs;

Parse Arg sIncFile
if (sIncFile='') Then sIncFile='paths.mak'

Say 'Current directory:'directory()
Say 'Generating 'directory()'\'sIncFile

/* Status */
Say 'Configuring the BT32 driver...'

/* delete old file */
Call SysFileDelete sIncFile

/* open target file */
If (Stream(sIncFile, 'C', 'OPEN WRITE' ) <> '') Then
Do
 Call LineOut sIncFile, '################################################################################'
 Call LineOut sIncFile, '# Generated by 'directory()'\config.cmd'
 Call LineOut sIncFile, '################################################################################'
 Call LineOut sIncFile, ''
 Call LineOut sIncFile, '################################################################################'
 Call LineOut sIncFile, '# Base directories'
 Call LineOut sIncFile, '# Note! These should be absolute paths!'
 Call LineOut sIncFile, '################################################################################'
 Call LineOut sIncFile, ''
 sBase=directory();
 Call LineOut sIncFile, 'DRV_BASE       :='sBase
 Call LineOut sIncFile, 'LX_BASE        :=$(LXAPI32DEV)'

 Call directory(sOldDir);
 Say ''
 Say 'Configuration completed!'
End
Else
Do
 Say 'oops, failed to open outputfile,' sIncFile;
 Exit 1;
End
Exit 0;

/*****************/
/* function area */
/*****************/
WriteSubDir: Procedure Expose sIncFile
 M=Arg(1)
 SubDir=Arg(2)
 If SubDir='' Then
 Do
  SubDir=Right(M,Length(M)-5)
 End
 If Length(M) < 16 Then
 Do
  M=Left(M'                ',16)
 End
 SubDir=Translate(SubDir,'abcdefghijklmnopqrstuvwxyz','ABCDEFGHIJKLMNOPQRSTUVWXYZ')
 Call LineOut sIncFile, M'=$(DRV_BASE)\'SubDir
Return
